// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class PlayGamesConstants
{
        public const string achievement_300_points = "CggI7Ofz8CoQAhAJ"; // <GPGSID>
        public const string achievement_100_points = "CggI7Ofz8CoQAhAG"; // <GPGSID>
        public const string leaderboard_medley = "CggI7Ofz8CoQAhAF"; // <GPGSID>
        public const string achievement_400_points = "CggI7Ofz8CoQAhAK"; // <GPGSID>
        public const string achievement_200_points = "CggI7Ofz8CoQAhAH"; // <GPGSID>
        public const string leaderboard_doubles = "CggI7Ofz8CoQAhAC"; // <GPGSID>
        public const string leaderboard_mystery = "CggI7Ofz8CoQAhAE"; // <GPGSID>
        public const string leaderboard_regular = "CggI7Ofz8CoQAhAB"; // <GPGSID>
        public const string leaderboard_3_lanes = "CggI7Ofz8CoQAhAD"; // <GPGSID>
        public const string achievement_50_points = "CggI7Ofz8CoQAhAI"; // <GPGSID>

}

